In [25]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
sent=['the glass of milk',
      'the glass of juice',
      'the cup of tea',
      'I am a good boy',
      'I am a gopd developer',
      'understand the meaning of words',
      'your videos are good']

In [27]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a gopd developer',
 'understand the meaning of words',
 'your videos are good']

In [28]:
## Define Vocabulary size:
voc_size=10000

In [29]:
# One hot representation:
one_hot_repr=[one_hot(words,voc_size) for words in sent]
one_hot_repr

[[3444, 3711, 8553, 2383],
 [3444, 3711, 8553, 7746],
 [3444, 980, 8553, 2516],
 [9866, 8919, 4827, 2360, 2904],
 [9866, 8919, 4827, 3348, 390],
 [2587, 3444, 355, 8553, 5299],
 [8014, 8479, 5966, 2360]]

In [ ]:
## Word embedding representation:
from tensorflow.keras.utils import pad_sequences
import numpy as np

In [ ]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 3444 3711 8553 2383]
 [   0    0    0    0 3444 3711 8553 7746]
 [   0    0    0    0 3444  980 8553 2516]
 [   0    0    0 9866 8919 4827 2360 2904]
 [   0    0    0 9866 8919 4827 3348  390]
 [   0    0    0 2587 3444  355 8553 5299]
 [   0    0    0    0 8014 8479 5966 2360]]


In [36]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential

sent_length = 8
embedding_vector_features = 10

model = Sequential()
model.add(
    Embedding(
        input_dim=voc_size,
        output_dim=embedding_vector_features,
        input_shape=(sent_length,)
    )
)
model.compile(optimizer='adam',loss='mean_squared_error')
model.summary()

d:\CODES\Gen AI course\envi\lib\site-packages\keras\src\layers\core\embedding.py:100: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)         │ (None, 8, 10)          │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step


array([[[-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [ 0.03719821, -0.01822975, -0.02653524, -0.03414454,
         -0.00122886, -0.04037752, -0.02445981,  0.03949486,
          0.03969068, -0.0471164 ],
        [ 0.04335549, -0.04305981, -0.03244193, -0.02236729,
         -0.0393752 ,  0.03487542,  0.00547533, -0.02862411,
          0.02318725,  0.0465509 ],
        [ 0.04031582, -0.04827076, -0.0407389 ,  0.0

In [41]:
embedded_docs[0]

array([   0,    0,    0,    0, 3444, 3711, 8553, 2383], dtype=int32)

In [43]:
model.predict(np.array([embedded_docs[0]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 100ms/step


array([[[-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [-0.02987682,  0.02350299, -0.02368779, -0.0052261 ,
         -0.00210303, -0.0259811 , -0.01809919,  0.0235444 ,
          0.00159875, -0.02888713],
        [ 0.03719821, -0.01822975, -0.02653524, -0.03414454,
         -0.00122886, -0.04037752, -0.02445981,  0.03949486,
          0.03969068, -0.0471164 ],
        [ 0.04335549, -0.04305981, -0.03244193, -0.02236729,
         -0.0393752 ,  0.03487542,  0.00547533, -0.02862411,
          0.02318725,  0.0465509 ],
        [ 0.04031582, -0.04827076, -0.0407389 ,  0.0